:twitter:
   :consumer_key: 252tvnEKujMv4hMuyRpvQ
   :consumer_secret: qiE6oDSvk2IQDIYDCyRI9BrpqFBr9FIu1jvJAr6RGJY

:facebook:
   :consumer_key: 190960770964408
   :consumer_secret: 667b79e3e9ea2f376cd8731dad8d4ff4